# Generated by Django 6.0.3 on 2026-03-17 01:38

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Optional description of the category"
            ),
        ),
    ]
