"""
Django settings for expense_tracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Standard Library
from datetime import timedelta
from pathlib import Path

# Third-party
import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-default-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "djangorestframework_camel_case",
    "corsheaders",
    # Local apps
    "expenses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "expense_tracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "expense_tracker.wsgi.application"


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================
# Database configuration using DATABASE_URL from environment
# Similar to connection strings in ASP.NET appsettings.json
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default to SQLite for development, can be overridden with DATABASE_URL
# Examples:
# - SQLite: sqlite:///db.sqlite3
# - PostgreSQL: postgresql://user:password@localhost:5432/dbname
# - Azure SQL: postgresql://user:password@server.postgres.database.azure.com:5432/dbname?sslmode=require

DATABASES = {
    "default": dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,  # Connection pooling (600 seconds)
        conn_health_checks=True,  # Check connection health
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# ============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    # Default pagination (returns paginated results)
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # 10 items per page
    # ========================================================================
    # AUTHENTICATION - UPDATED FOR JWT
    # ========================================================================
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT!
        "rest_framework.authentication.SessionAuthentication",  # Keep for browsable API
    ],
    # ========================================================================
    # PERMISSIONS - UPDATED TO REQUIRE AUTH
    # ========================================================================
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Changed from AllowAny!
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Renderers con camelCase
    "DEFAULT_RENDERER_CLASSES": [
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ],
    # Parsers con camelCase
    "DEFAULT_PARSER_CLASSES": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
    ],
    # ========================================================================
    # FILTERING, SEARCHING, ORDERING - ADD THIS SECTION
    # ========================================================================
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",  # Filtering
        "rest_framework.filters.SearchFilter",  # Search
        "rest_framework.filters.OrderingFilter",  # Ordering
    ],
    # Compare to C#:
    # Similar to adding middleware for query processing
    # Like: app.UseQueryStringValueProvider()
}

# ============================================================================
# DRF-SPECTACULAR (Swagger/OpenAPI) CONFIGURATION
# ============================================================================

# ============================================================================
# DRF-SPECTACULAR (Swagger/OpenAPI) CONFIGURATION
# ============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Expense Tracker API",
    "DESCRIPTION": "A REST API for personal expense tracking with JWT authentication",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Swagger UI settings
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,  # Remember auth between page reloads
        "displayOperationId": True,
    },
    # Schema settings
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "CAMELIZE_NAMES": True,
    # ========================================================================
    # JWT AUTHENTICATION CONFIGURATION - ADD THIS
    # ========================================================================
    "AUTHENTICATION_WHITELIST": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # Security scheme for JWT
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT token authentication. Get your token from /api/auth/login/ or /api/auth/register/",
            }
        }
    },
    # Default security (all endpoints require JWT)
    "SECURITY": [{"jwtAuth": []}],
}

# ============================================================================
# JWT AUTHENTICATION CONFIGURATION
# ============================================================================

SIMPLE_JWT = {
    # Token lifetimes
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Access token expires after 60 minutes
    # Short-lived for security
    # Like: JwtSecurityTokenHandler.TokenLifetime in C#
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Refresh token expires after 7 days
    # Long-lived to avoid frequent re-login
    # User stays logged in for a week
    # Token types
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Authorization: Bearer <token>
    # Standard HTTP Bearer authentication
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    # Header name in Django (prefixed with HTTP_)
    # Token claims
    "USER_ID_FIELD": "id",
    # Which user field to include in token
    "USER_ID_CLAIM": "user_id",
    # Name of the claim in JWT payload
    # Token behavior
    "ROTATE_REFRESH_TOKENS": True,
    # Issue new refresh token on refresh
    # Increases security
    "BLACKLIST_AFTER_ROTATION": True,
    # Blacklist old refresh tokens
    # Prevents token reuse
    "UPDATE_LAST_LOGIN": True,
    # Update user.last_login on token generation
    # Algorithm
    "ALGORITHM": "HS256",
    # HMAC with SHA-256
    # Like: SecurityAlgorithms.HmacSha256 in C#
    # Signing key (from SECRET_KEY)
    "SIGNING_KEY": SECRET_KEY,
    # Use Django's SECRET_KEY to sign tokens
    # In production, use environment variable
    # Token verification
    "VERIFY_SIGNATURE": True,
    # Always verify token signature
    "VERIFY_EXP": True,
    # Verify expiration time
    "LEEWAY": 0,
    # No leeway for expiration (strict)
    # JSON encoder
    "JSON_ENCODER": None,
}

# ==============================================================================
# CORS CONFIGURATION
# ==============================================================================
# Cross-Origin Resource Sharing settings for frontend integration
# Similar to CORS configuration in ASP.NET Core

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allowed origins from environment variable
# In development: http://localhost:3000,http://localhost:5173
# In production: https://yourfrontend.com
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:5173",
    cast=Csv(),
)

# Allowed methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Allowed headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ==============================================================================
# STATIC FILES CONFIGURATION
# ==============================================================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# WhiteNoise serves static files in production (similar to wwwroot in ASP.NET)

STATIC_URL = "static/"

# Directory where collectstatic will collect static files for deployment
# Similar to publishing wwwroot folder in ASP.NET
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional locations of static files
STATICFILES_DIRS: list[str] = [
    # Add paths to your static files here if needed
    # Example: BASE_DIR / 'static',
]

# WhiteNoise storage backend (with compression and caching)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================
# Logging configuration for debugging and production monitoring
# Similar to ILogger in ASP.NET Core

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": config("LOG_LEVEL", default="INFO"),
            "propagate": True,
        },
        "expenses": {
            "handlers": ["console", "file"],
            "level": config("LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}


# Compare to C# TokenValidationParameters:
# new TokenValidationParameters {
#     ValidateIssuer = true,
#     ValidateAudience = true,
#     ValidateLifetime = true,
#     ValidateIssuerSigningKey = true,
#     IssuerSigningKey = new SymmetricSecurityKey(key),
#     ClockSkew = TimeSpan.Zero
# }
